[package]
name = "rust-iot-monitor"
version = "0.1.0"
description = "DEV - Build: 08-08-2025"
edition = "2021"

[dependencies]
clap = { version = "4.5.43", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
socket2 = { version = "0.6.0-rc.2" }