[build]
target = "x86_64-unknown-linux-musl"

# [target.x86_64-unknown-linux-gnu]
# linker = "rust-lld"

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

# target config for Embedded Computer with armv7l arch
# [target.armv7-unknown-linux-gnueabi]
# linker = "arm-linux-gnueabi-gcc"
# rustflags = ["-C", "target-feature=+crt-static"]
